### ISSUE TITLE
Settings menu does not open (Error: Requiring Json, version none: Typelib file for namespace 'Json' (any version) not found)

### ISSUE THREAD

**Issue by The-Nyla** [neuromorph/custom-osd#17]
![image](https://github.com/user-attachments/assets/02934d5d-5f6f-4c41-844a-a7efb51d0c9b)

I'm running Vanilla OS, and when attempting to open the settings for Custom OSD, I run into this error

**Comment by neuromorph** [comment]
This is duplicate of issue #13 

Resolution from that issue for reference:

This error happens due to missing introspection package. While the libjson-glib is installed by default as expected, the corresponding introspection package is missing for some reason.

Please install following tiny package to fix it. You can use synaptic package manager to install it, if you wish.
Package: `gir1.2-json-1.0`

The 'gir' is the Gnome Introspection Repository. This helps it find the API for the lib already installed.

Thanks!

**Comment by The-Nyla** [comment]
Thanks!

**Comment by The-Nyla** [comment]
I've just installed the package and restarted my system, but the same error persists for some reason

**Comment by neuromorph** [comment]
Maybe the Vanilla OS is more vanilla than others. 
Check if you have libjson installed. You can run:
`dpkg --list | grep libjson-glib-1.0-0`

If that has no results, then in general:
`dpkg --list | grep json`
and look for similar libs installed.

You may need to install libjson-glib-1.0-0 if none available.

**Comment by The-Nyla** [comment]
seems to be installed already
![image](https://github.com/user-attachments/assets/5da00963-9bbf-4d25-be26-ea84b29b28c0)

**Comment by neuromorph** [comment]
Whoa!
So it does seem installed.
To be sure, do you get similar output for the gir package by running:
`dpkg --list | grep gir1.2-json-1.0`

That should fix the issue so please double-check. I am not sure of anything else as of now.

**Comment by The-Nyla** [comment]
![image](https://github.com/user-attachments/assets/018696f8-61b5-4e96-b9f0-ab05e4ed940a)
error still persists, pretty strange. I'd assume it's probably something to do with Vanilla OS, because other than that I have no clue what could be the issue

**Comment by neuromorph** [comment]
The issue as per the error is that some library for 'json' is missing. Though need to find which one. 
Maybe you can compare with the output I get. This is part of it, other than this there are few related to 'node' and 'python' that appear in the result but these should be more relevant.

```
$ dpkg --list | grep json
ii  gir1.2-json-1.0:amd64                            1.8.0-2build2                             amd64        GLib JSON manipulation library (introspection data)
ii  libcjson1:amd64                                  1.7.17-1                                  amd64        Ultralightweight JSON parser in ANSI C
ii  libfastjson4:amd64                               1.2304.0-1build1                          amd64        fast json library for C
ii  libjson-c5:amd64                                 0.17-1build1                              amd64        JSON manipulation library - shared library
ii  libjson-glib-1.0-0:amd64                         1.8.0-2build2                             amd64        GLib JSON manipulation library
ii  libjson-glib-1.0-common                          1.8.0-2build2                             all          GLib JSON manipulation library (common files)
ii  libunity-scopes-json-def-desktop                 7.1.4+19.04.20190319-6build4              all          binding to get places into the launcher - desktop def fi
```

Can you find something missing for you ? we can look into that.

**Comment by The-Nyla** [comment]
Here's what I got

$ dpkg --list | grep json
ii  gir1.2-json-1.0:amd64                                   1.8.0-2+b1                                amd64        GLib JSON manipulation library (introspection data)
ii  libcjson1:amd64                                         1.7.18-3                                  amd64        Ultralightweight JSON parser in ANSI C
ii  libfastjson4:amd64                                      1.2304.0-1+b1                             amd64        fast json library for C
ii  libjson-c5:amd64                                        0.17-1+b1                                 amd64        JSON manipulation library - shared library
ii  libjson-glib-1.0-0:amd64                                1.8.0-2+b1                                amd64        GLib JSON manipulation library
ii  libjson-glib-1.0-common                                 1.8.0-2                                   all          GLib JSON manipulation library (common files)
ii  libjsoncpp25:amd64                                      1.9.5-6+b2                                amd64        library for reading and writing JSON for C++
ii  node-json-buffer                                        3.0.1+~3.0.0-1                            all          JSON functions that can convert buffers.
ii  node-json-parse-better-errors                           1.0.2+~cs3.3.1-3                          all          JSON.parse() with context information on error
ii  node-json-schema                                        0.4.0+~7.0.11-1                           all          JSON Schema validation and specifications
ii  node-json-schema-traverse                               1.0.0-3                                   all          Json schema traversal package
ii  node-json-stable-stringify                              1.0.2+repack1+~cs1.0.34-2                 all          deterministic JSON.stringify()
ii  node-json5                                              2.2.3+dfsg-1                              all          JSON for the ES5 era
ii  node-jsonify                                            0.0.1-1                                   all          JSON without touching any globals
ii  node-jsonparse                                          1.3.1-10                                  all          Pure javascript JSON streaming parser for node.js
ii  node-parse-json                                         5.2.0+~cs5.1.7-2                          all          parse JSON with more helpful errors
ii  node-promzard                                           0.3.0-2                                   all          Promzard provides a prompting json wizard
ii  node-read-package-json                                  5.0.2+~2.0.0-2                            all          Read package.json for npm module for Node.js
ii  node-read-pkg                                           5.2.0-2                                   all          Read a package.json file
ii  node-strip-json-comments                                4.0.0-4                                   all          Node.js module to strip comments from JSON

**Comment by neuromorph** [comment]
The libs seem to be installed. This should have allowed finding Json.
Has the error changed now or is it still exactly the same?

**Comment by The-Nyla** [comment]
Ah, sorry for the late response, but the error seems to stay the same
![image](https://github.com/user-attachments/assets/e139e909-e13d-40f2-a7eb-1ef585c22bbd)

**Comment by jerm00** [comment]
> This is duplicate of issue #13
> 
> Resolution from that issue for reference:
> 
> This error happens due to missing introspection package. While the libjson-glib is installed by default as expected, the corresponding introspection package is missing for some reason.
> 
> Please install following tiny package to fix it. You can use synaptic package manager to install it, if you wish. Package: `gir1.2-json-1.0`
> 
> The 'gir' is the Gnome Introspection Repository. This helps it find the API for the lib already installed.
> 
> Thanks!

i had the same error, this fixed it for me. thanks a lot! ubuntu 24.04.1

**Comment by suhanyujie** [comment]
> Ah, sorry for the late response, but the error seems to stay the same ![image](https://private-user-images.githubusercontent.com/79489385/363537913-e139e909-e13d-40f2-a7eb-1ef585c22bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNDI1NzYsIm5iZiI6MTczNjA0MjI3NiwicGF0aCI6Ii83OTQ4OTM4NS8zNjM1Mzc5MTMtZTEzOWU5MDktZTEzZC00MGYyLWE3ZWItMWVmNTg1YzIyYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDAxNTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YTRlNDk2MTUwZjMxZTMxZTI0NmUxYWExMzExZGFhZTE4NTA0ZTdmZjAzNDgzMmRjMjI2ZjliZjllMmZlM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fO7D3Dits7A807nEC2R7ypXltnX_ToquCYSX5dRCPwM)

You may need to restart gnome-shell: 
1.alt + f2
2.type `r`
3.`enter`
